application/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from core import views as core_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),


    url(r'^blog/', include('blog.urls',
                           namespace='blog',
                           app_name='blog')),

    url(r'^', include('account.urls')),
    url('social-auth/', include('social_django.urls', namespace='social')),

]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # post views
    #url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^$', views.post_list, name='post_list'),

    url(r'^create/$', views.PostCreate.as_view(), name='create'),

    url(r'^(?P<pk>\d+)/edit/$', views.PostEdit.as_view(),
        name='edit'),

    url(r'^(?P<pk>\d+)/delete/$', views.PostDelete.as_view(),
        name='delete'),

    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),

    url(r'^(?P<pk>\d+)/$',
        views.post_detail,
        name='post_detail'),

    url(r'^(?P<pk>\d+)/share/$', views.post_share, name='post_share'),
]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=255, blank=True, null=True)
    slug = models.SlugField(max_length=255, unique_for_date='publish')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)


    def __unicode__(self):
        return unicode(self.title) or u''



"""
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='blog', verbose_name=u'Автор')
    categories = models.ManyToManyField('categories.Category',blank=True, related_name='blog' )
    name = models.CharField(max_length=255)
    is_archive = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = u'Пост'
        verbose_name_plural = u'Посты'
        ordering = 'name', 'id'

    def __unicode__(self):
        return self.name
"""



class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='blog_comments')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __unicode__(self):
        return 'Comment by {} on {}'.format(self.author, self.post)

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404, reverse
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, CreateView, UpdateView,DeleteView
from django import forms
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count


class PostListView(ListView):
    queryset = Post.objects.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


class PostCreate(CreateView):
    model = Post
    fields = 'title', 'body', 'status', 'tags'
    template_name = 'blog/post/create.html'
    context_object_name = 'post'
    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.object.pk})
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(PostCreate, self).form_valid(form)

class PostEdit(UpdateView):
    model = Post
    fields = 'title', 'body', 'status', 'tags'
    template_name = 'blog/post/edit.html'
    context_object_name = 'post'
    def get_success_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.object.pk})
    def get_queryset(self):
        queryset = super(PostEdit, self).get_queryset()
        return queryset.filter(author=self.request.user)

class PostDelete(DeleteView):
    model = Post
    fields = 'title',
    template_name = 'blog/post/delete.html'
    context_object_name = 'post'
    def get_success_url(self):
        return reverse('blog:post_list')



def post_list(request, tag_slug=None):
    object_list = Post.objects.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post/list.html', {'page': page,
                                                   'posts': posts,
                                                   'tag': tag})


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('body', )



def post_detail(request, pk=None):
    post = get_object_or_404(Post, id=pk, status='published')
    # List of active comments for this post
    comments = post.comments.filter(active=True)

    if request.method == 'POST':
        # A comment was posted


        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            new_comment.author = request.user
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.objects.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})



class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


def post_share(request, pk=None):
    # Retrieve post by id
    post = get_object_or_404(Post, id=pk, status='published')
    sent = False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = reverse('blog:post_detail', kwargs={'pk': post.pk})
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@admin.com',[cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})

blog/templates/blog/post/create.html
{% extends "blog/base.html" %}

{% block title %}Creating post{% endblock %}
{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Create">
    </form>
{% endblock %}

blog/templates/blog/post/delete.html
{% extends "blog/base.html" %}
{% block title %}Deleting {{ post }}{% endblock %}
{% block content %}
   <form action="" method="post">{% csrf_token %}
       <p>Are you sure you want to delete "{{ post }}"?</p>
       <input type="submit" value="I'm sure" />
    </form> <br>

    <form action="{% url "blog:edit" pk=post.pk %}">
        <button type="submit">I'm not sure</button>
    </form>

{% endblock %}

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}

{% block bar %}

            <li class="nav-item active">
              <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item ">
              <a class="nav-link" href="/blog/">Blog</a>
            </li>



            {% if request.user.is_authenticated %}
                <li class="nav-item">
                <a class="nav-link disabled" href="{% url "instruments" %}">Instruments</a>
                </li>

                <li class="nav-item">
                <a class="nav-link disabled" href="{% url "history" %}">History</a>
                </li>

                <li class="nav-item ">
                <a class="nav-link" href="{% url "blog:edit" pk=post.pk %}">Edit post</a>
                </li>

                <li class="nav-item ">
                <a class="nav-link" href="{% url 'logout' %}?next=/login">Sign-out</a>
                </li>

            {% else %}
                <li class="nav-item ">
                <a class="nav-link" href="/login/">Sign-in</a>
                </li>
            {% endif %}

            {% endblock %}


{% block content %}

    <h1><a href="{% url "blog:post_list" %}">{{ post.title }}</a></h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>

         <p class="tags">

            {% for tag in post.tags.all %}
                <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                    <i>{{ tag.name }}</i>
                </a>

            {% endfor %}
        </p>


    {{ post.body|linebreaks }}

    <p>
    <a href="{% url "blog:post_share" pk=post.id %}">Share this post</a>
    </p>

<br> <br><br>
    {% if  similar_posts%}
        <i>Similar posts:</i>
        {% for post in similar_posts %}
            <p>
                <a href="{% url "blog:post_detail" pk=post.id %}">{{ post.title }}</a>
            </p>


        {% endfor %}
    {% endif %}


<br> <br><br>
    {% with comments.count as total_comments %}
    <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }}:
    </h2>
    {% endwith %}

    {% for comment in comments %}
    <div class="comment">
        <p class="info">
             by {{ comment.author  }}:
        </p>
        {{ comment.body|linebreaks }}

        <p class="info">
            {{ comment.created }}
        </p>
    </div>

        {% endfor %}


    {% if new_comment %}
         <h2>Your comment has been added.</h2>
    {% else %}

         {% if request.user.is_authenticated %}
            <h2>Add a new comment</h2>
            <form action="." method="post">
                {{ comment_form.body }}
                {% csrf_token %}
                <p><input type="submit" value="Add comment"></p>
            </form>

         {% endif %}

    {% endif %}


{% endblock %}

blog/templates/blog/post/edit.html
{% extends "blog/base.html" %}
{% block title %}Editing {{ post }}{% endblock %}
{% block content %}
    <form action="" method="post" >
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Edit">


    </form> <br>
        <form action="{% url "blog:delete" pk=post.pk %}">
            <button type="submit">Delete</button>
        </form>


{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}Blog{% endblock %}

{% block bar %}

            <li class="nav-item ">
              <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item active">
              <a class="nav-link" href="/blog/">Blog</a>
            </li>



            {% if request.user.is_authenticated %}
                <li class="nav-item">
                <a class="nav-link disabled" href="{% url "instruments" %}">Instruments</a>
                </li>

                <li class="nav-item">
                <a class="nav-link disabled" href="{% url "history" %}">History</a>
                </li>

                <li class="nav-item ">
                <a class="nav-link" href="{% url 'blog:create'  %}">New post</a>
                </li>

                <li class="nav-item ">
                <a class="nav-link" href="{% url 'logout' %}?next=/login">Sign-out</a>
                </li>

            {% else %}
                <li class="nav-item ">
                <a class="nav-link" href="/login/">Sign-in</a>
                </li>
            {% endif %}

            {% endblock %}




{% block content %}

    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}





    {% for post in posts %}
        <h2>
            <a href="{% url "blog:post_detail" pk=post.id %}">{{ post.title }}</a>
        </h2>


        <p class="date">
            by {{ post.author }}
            <br> {{ post.publish }} <br>

            {% for tag in post.tags.all %}
                <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                    <i>{{ tag.name }}</i>
                </a>

            {% endfor %}


        </p>



        {{ post.body|truncatewords:30|linebreaks }}


    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ cd.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}